### ISSUE TITLE
Add support for GBxCart RW v1.3

### ISSUE THREAD

**Issue by insidegadgets** [KevinVitale/CartBoy#10] opened 2019-10-14 13:14 UTC
Hi Kevin,

It appears that GBxCart RW v1.3 isn't working correctly, it doesn't change to 5V (I can't recall if it ever worked?). The voltage selection is software controlled. 

You just need to request the PCB version (#define READ_PCB_VERSION 'h') and if it matches v1.3 (#define PCB_1_3 4), it should send (#define VOLTAGE_5V '5') and wait a few hundred milliseconds just to be safe.

Thanks!

**Comment by KevinVitale** [comment] 2019-10-17 14:20
Okay! Thanks @insidegadgets. I'll see what I can do.

**Comment by KevinVitale** [comment] 2019-11-03 19:47
@insidegadgets: Can you test the build I added to this pull-request ---> #11.

**Comment by insidegadgets** [comment] 2019-11-04 00:48
Thanks Kevin, I can confirm it does switch to 5V however it doesn't appear to read the cartridge information after that, the refresh button doesn't work.

**Comment by KevinVitale** [comment] 2019-11-04 01:40
@insidegadgets thanks for the quick reply! I fixed a deadlocking issue that was likely the cause of what you're describing. Another binary attached; can you give it a try?

See #11 for download

**Comment by insidegadgets** [comment] 2019-11-04 02:44
Thanks! Confirmed it works now! :)

**Comment by KevinVitale** [comment] 2019-11-04 03:06
Fixed in #11.

**Closed as completed by KevinVitale** 2019-11-04 03:06 UTC
